config/routes.rb
Rails.application.routes.draw do
	root to: "pages#index"

	resources :users

	get "/login", to: "users#login"
	post "/logresult", to: "users#logresult"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/pretty_email.validatable.rb
require 'email'

module PrettyEmailValidatable
  extend ActiveSupport::Concern

  class PrettyEmailValidator < ActiveModel::EachValidator

    def validate_each(record, attribute, value)
      begin
        a = Mail::Address.new(value)
      rescue Mail::Field::ParseError
        record.errors[attribute] << (options[:message] || "is not an email")
      end

      # regexp from http://guides.rubyonrails.org/active_record_validations.html
      value = a.address
      unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
        record.errors[attribute] << (options[:message] || "is not an email")
      end
    end

  end
end

app/models/user.rb
class User < ApplicationRecord
	validates :firstname, :lastname, :email, :password,:country, :city, :house_number, presence: true
	validates :house_number, numericality: { only_integer: true  }	
	validates :firstname, :lastname, :country, :city, format: { with: /\A[a-zA-Z]+\z/, message: ":only letters!"}
	validates :email, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "has invalid email adress"}
	validates :password, length: {in: 3..12}
	validates :password, confirmation: true
	validates :email, uniqueness: true
	#validates :firstname, :lastname, :email, :password, presence: true
	#validates :lastname, :email, :password,  uniqueness: true
	#validates :password, numericality: true
#validates :password, numericality: { only_integer: true }
	#include PrettyEmailValidatable
	#validates :pretty_email, email: true
	#validates :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
#validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	#validates :email, email_format: { message: "doesn't look like an email address" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end

  def login
  end

  def logresult 
  	pp params[:user][:email]
  	@user = User.find_by_email_and_password(params[:user][:email], params[:user][:password])
  	if @user!=nil
  		session[:user] = @user.id
  		redirect_to user_path(@user.id)
  	end
  end

  def show
  	@user = User.find(session[:user])
  end

  def destroy
  	@user = User.find(session[:user])
  	@user.destroy = nil
  end


 private 

  def user_params 
  	params.require(:user).permit(:lastname, :firstname, :email, :password, :password_confirmation, :country, :city, :house_number)
  end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proj</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<%= link_to "Registration", new_user_path %> or <%= link_to "Login", login_path %>

app/views/users/login.html.erb
<%= form_for :user, url: logresult_path do |f| %>

	<%= f.label :email %>
	<%= f.text_field :email %><br />

	<%= f.label :password %>
	<%= f.text_field :password %><br />

	<%= f.submit "Save" %>

<% end %>

app/views/users/new.html.erb
<%= form_for :user, url: users_path do |f| %>
 <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>

	<%= f.label :firstname %><br>
	<%= f.text_field :firstname %><br />

	<%= f.label :lastname %><br>
	<%= f.text_field :lastname %><br />

	<%= f.label :email %><br>
	<%= f.text_field :email %><br />

	<%= f.label :password %><br>
	<%= f.password_field :password %><br />

	<%= f.label :password_confirmation %><br>
	<%= f.password_field :password_confirmation %><br />

	<%= f.label :country %><br>
	<%= f.text_field :country %><br />

	<%= f.label :city %><br>
	<%= f.text_field :city %><br />

	<%= f.label :house_number %><br>
	<%= f.text_field :house_number %><br />


	<%= f.submit "Save" %>

<% end %>

app/views/users/show.html.erb
Firstname: <%= @user.firstname %>
Lastname: <%= @user.lastname %>